### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [everitoken/evt#139]
[Two extra null pointer checks are not needed](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") in [the function “token_database_impl::close”](https://github.com/everitoken/evt/blob/02b466f87dfb0feebfb9d611739d00dc763edb6f/libraries/chain/token_database.cpp#L408 "Update candidate").

**Comment by harrywong** [comment]
Hi @elfring thanks for pointing out! Can you make a PR for this?

**Comment by ceeji** [comment]
Great!

**Comment by elfring** [comment]
Thanks for your small source code improvement.
