### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [everitoken/evt#143]
I would like to point out that identifiers like “[`__internal`](https://github.com/everitoken/evt/blob/94acd999c25e3a3d40667bc70072f24562b7fddb/libraries/chain/token_database.cpp#L37 "Update candidate")” and “[`__prepare_register`](https://github.com/everitoken/evt/blob/1fe75bf56162cbce6d89a12209e39b50e1a7da53/plugins/history_plugin/evt_pg_query.cpp#L25 "Another update candidate")” [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by harrywong** [comment]
Thanks! I didn't know this limitations before.

**Comment by elfring** [comment]
Thanks for [your source code improvement](https://github.com/everitoken/evt/commit/86eac10ff3185bd2752540ce8ec9ac006081cd4a "Renaming of identifiers").
