### ISSUE TITLE
Add transfer permission to FT

### ISSUE THREAD

**Issue by harrywong** [everitoken/evt#144]
Currently we only support transfer permission in NFT domain not in FT. We'd like to add transfer permission to FTs for better flexibility. And due to this flexibility, users may not notice there's a chance that the issuer of FT can change the transfer permission at any time. Additional reserved meta field `.disable-set-transfer` will be added for explicit declaration of cannot setting transfer permission.

**Comment by ceeji** [comment]
transfer permission is already implemented in everiToken 3.1 (FT v2).
