### ISSUE TITLE
  CXX_STANDARD is set to invalid value '17'

### ISSUE THREAD

**Issue by shangmacun** [everitoken/evt#33]
WARNING: Target "chainbase_test" requests linking to directory "/usr/include/openssl".  Targets may link only to libraries.  CMake is dropping the item.
CMake Error at libraries/utilities/CMakeLists.txt:22 (add_library):
  CXX_STANDARD is set to invalid value '17'

CMake Error at libraries/appbase/CMakeLists.txt:45 (add_library):
  CXX_STANDARD is set to invalid value '17'

CMake Error at libraries/appbase/examples/CMakeLists.txt:1 (add_executable):
  CXX_STANDARD is set to invalid value '17'

CMake Error at libraries/rocksdb/CMakeLists.txt:160 (add_library):

**Comment by harrywong** [comment]
Please use latest CMake version. (aka. 3.11)

**Comment by harrywong** [comment]
C++ 17 is supported by CMake starts at 3.8

**Comment by shangmacun** [comment]
已解决
