### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by shangmacun** [everitoken/evt#34]
[ 90%] Building CXX object libraries/chain/CMakeFiles/evt_chain.dir/address.cpp.o
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://bugzilla.redhat.com/bugzilla> for instructions.
make[3]: *** [libraries/chain/CMakeFiles/evt_chain.dir/address.cpp.o] Error 4
make[2]: *** [libraries/chain/CMakeFiles/evt_chain.dir/all] Error 2
make[1]: *** [programs/evtwd/CMakeFiles/evtwd.dir/rule] Error 2
make: *** [evtwd] Error 2

**Comment by shangmacun** [comment]
内存不足？

**Comment by harrywong** [comment]
What the compiler version do you use?

**Comment by shangmacun** [comment]
devtoolset-7

gcc version 7.3.1 20180303 (Red Hat 7.3.1-5) (GCC)

**Comment by harrywong** [comment]
ok. try to reduce the number of parallel jobs when compiling.
