### ISSUE TITLE
When I did that with docker, I got an error

### ISSUE THREAD

**Issue by wbm0701** [everitoken/evt#94]
ERROR: Volume evtwd-data-volume declared as external, but could not be found. Please create the volume manually using `docker volume create --name=evtwd-data-volume` and try again.

**Comment by ceeji** [comment]
Yes. you need to create a volume using that command if you use external volume for docker.

**Comment by wbm0701** [comment]
> 是。如果使用docker的外部卷，则需要使用该命令创建卷。

I tried, and it turned out to be a mistake:
[root@localhost usr]# docker volume create --name=evtwd-data-volume
evtwd-data-volume
[root@localhost usr]# docker-compose up --no-start evtwd
ERROR: Volume evtd-data-volume declared as external, but could not be found. Please create the volume manually using `docker volume create --name=evtd-data-volume` and try again.

**Comment by wbm0701** [comment]
> 是。如果使用docker的外部卷，则需要使用该命令创建卷。

Is there something wrong with my y'm'l file？






version: "3"

services:
  evtd:
    build:
      context: .
    image: everitoken/evt:latest
    command: /opt/evt/bin/evtd.sh --data-dir /opt/evt/data
    hostname: 'ectd'
    ports:
      - 8888:8888
      - 9876:9876
    expose:
      - "8888"
    volumes:
      - evtd-data-volume:/opt/evt/data

  evtwd:
    image: everitoken/evt:latest
    command: /opt/evt/bin/evtwd --wallet-dir /opt/evt/data --http-server-address=127.0.0.1:9999
    hostname: 'evtwd'
    links:
      - evtd
    volumes:
      - evtwd-data-volume:/opt/evt/data

volumes:
  evtd-data-volume:
    external: true
  evtwd-data-volume:
    external: true
~

**Comment by wbm0701** [comment]
> 是。如果使用docker的外部卷，则需要使用该命令创建卷。

My friend, may I have your contact information? I want to ask you some questions

**Comment by harrywong** [comment]
Two volumes are needed here, `evtd-data-volume` and `evtwd-data-volume`. So please create both, then you can start evtwd container.

**Comment by wbm0701** [comment]
> 这里需要两卷，`evtd-data-volume`和`evtwd-data-volume`。所以请创建两个，然后你可以启动evtwd容器。



> Two volumes are needed here, `evtd-data-volume` and `evtwd-data-volume`. So please create both, then you can start evtwd container.

thank you !!! 这个可以了

**Comment by wbm0701** [comment]
evtc --help

报下面的错
terminate called after throwing an instance of 'CLI::OptionAlreadyAdded'
  what():  -x,--expiration is already added

**Comment by harrywong** [comment]
拉最新的docker镜像
Plz pull latest docker image

**Comment by wbm0701** [comment]
> 拉最新的docker镜像
> Plz pull latest docker image

我拉这

**Comment by wbm0701** [comment]
谢谢，我都测试成功啦！！~
